In [1]:
import pandas as pd

data = pd.read_csv("reconciled_articles.csv", sep = "\t").dropna(subset=["Data location"])

In [2]:
data

,DOI,Organism,Tissue,Technique,Data location,itemLabel,normalized_doi,item
4,10.1093/NAR/GKL050,Mouse,ICM,aRNA amplification,GSE4309,An improved single-cell cDNA amplification met...,10.1093/NAR/GKL050,Q25256621
9,10.1038/NMETH.1315,Mouse,Oocyte,Tang,GSE14605,mRNA-Seq whole-transcriptome analysis of a sin...,10.1038/NMETH.1315,Q28240611
12,10.1016/J.STEM.2010.03.015,Mouse,Embryo,Tang,GSE20187,Tracing the derivation of embryonic stem cells...,10.1016/J.STEM.2010.03.015,Q34619418
13,10.1101/GR.110882.110,Mouse,Culture,STRT-seq,GSE29087,Characterization of the single-cell transcript...,10.1101/GR.110882.110,Q24598443
14,10.1371/JOURNAL.PONE.0021208,Mouse,Embryo,Tang,GSE22182,Deterministic and stochastic allele specific g...,10.1371/JOURNAL.PONE.0021208,Q33952225
...,...,...,...,...,...,...,...,...
1017,10.1126/SCIENCE.ABA7721,Human,NaN,sci-RNA-seq3,GSE156793,A human cell atlas of fetal gene expression,10.1126/SCIENCE.ABA7721,Q102053616
1022,10.1038/S41467-020-20082-7,Human,Thymus,Chromium,GSE159745,Reconstitution of a functional human thymus by...,10.1038/S41467-020-20082-7,Q104459140
1025,10.1016/J.STEM.2020.11.015,Human,"Bone marrow, Liver",Smart-seq2,E-MTAB-9067,Integrative Single-Cell RNA-Seq and ATAC-Seq A...,10.1016/J.STEM.2020.11.015,Q104558740
1029,10.1016/J.CELL.2020.12.016,Human,Intestine,Chromium,GSE158702,Spatiotemporal analysis of human intestinal de...,10.1016/J.CELL.2020.12.016,Q104754414
1030,10.1016/J.CELREP.2020.108573,Human,Bone marrow,Chromium,GSE158490,Single-Cell Mapping of Progressive Fetal-to-Ad...,10.1016/J.CELREP.2020.108573,Q104754435

Reconciling GSEs:

1 - get just GSEs

2 - prepare Quickstatements

In [3]:
data =data[["MTAB" in string for string in data["Data location"]]]
len(data)

66

In [4]:
def explode_commas(df, column):

    strings = []
    for string in df[column]:
        
        if "," in string:
            array = string.split(", ")
            strings.append(array)
        else:
            strings.append(string)

    df[column] = strings
    print(df)
    return(df.explode(column))

Let us explode those commas

In [5]:
exploded_data = explode_commas(data, "Data location")

print(len(data))
print(len(exploded_data))

                               DOI  \
22                 10.1038/NCB2798
25              10.1038/NMETH.2645
37    10.1016/J.CELREP.2014.04.011
49                10.1038/NBT.3102
58                10.1038/NBT.3209
...                            ...
888     10.1038/S41467-020-15326-5
931      10.1038/S41587-020-0497-0
975   10.1016/J.DEVCEL.2020.07.018
999   10.1016/J.CELREP.2020.108263
1025    10.1016/J.STEM.2020.11.015

                                               Organism              Tissue  \
22                                                Mouse              Embryo
25                                   Arabidopsis, Mouse        Root, Spleen
37                                                Mouse              Spleen
49                                                Mouse             Culture
58                                Platynereis dumerilii                 NaN
...                                                 ...                 ...
888                                               Human             Culture
931                                        Human, Mouse                 NaN
975   Cynomolgus macaque, Human, Mouse, Pig, Rhesus ...              Testis
999                                               Human             Culture
1025                                              Human  Bone marrow, Liver

         Technique Data location  \
22            Tang   E-MTAB-1178
25    SMARTer (C1)   E-MTAB-1499
37    SMARTer (C1)   E-MTAB-2512
49    SMARTer (C1)   E-MTAB-2805
58    SMARTer (C1)   E-MTAB-2865
...            ...           ...
888       Chromium   E-MTAB-7742
931     Smart-seq3   E-MTAB-8735
975       Chromium   E-MTAB-8979
999       Chromium   E-MTAB-9154
1025    Smart-seq2   E-MTAB-9067

                                              itemLabel  \
22    A tripartite transcription factor network regu...
25    Accounting for technical noise in single-cell ...
37    Single-cell RNA sequencing reveals T helper ce...
49    Computational analysis of cell-to-cell heterog...
58    High-throughput spatial mapping of single-cell...
...                                                 ...
888   Identification of cell surface markers and est...
931   Single-cell RNA counting at allele and isoform...
975   Single-Cell RNA Sequencing of the Cynomolgus M...
999   Single-Cell Transcriptomics of Parkinson's Dis...
1025  Integrative Single-Cell RNA-Seq and ATAC-Seq A...

                    normalized_doi        item
22                 10.1038/NCB2798   Q24608859
25              10.1038/NMETH.2645   Q42774165
37    10.1016/J.CELREP.2014.04.011   Q33691866
49                10.1038/NBT.3102   Q30884891
58                10.1038/NBT.3209   Q30930642
...                            ...         ...
888     10.1038/S41467-020-15326-5   Q90776167
931      10.1038/S41587-020-0497-0   Q96230193
975   10.1016/J.DEVCEL.2020.07.018   Q98469310
999   10.1016/J.CELREP.2020.108263  Q100540790
1025    10.1016/J.STEM.2020.11.015  Q104558740

[66 rows x 8 columns]
66
66

/home/lubianat/.local/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [7]:
def make_mtab_url(mtab):
    return('"' + "https://www.ebi.ac.uk/arrayexpress/experiments/" + mtab + '"')

In [8]:
from time import gmtime, strftime


with open("external_data_11_02_2021.qs", "w") as f:
    for i, row in exploded_data.iterrows():
        s = row["item"]
        p = "P1325" # external data available at
        o = make_mtab_url(row["Data location"])
        rp1 = "S248"
        ro1 = "Q103034964"
        rp2 = "S854"
        ro2 = '"https://www.nxn.se/single-cell-studies/data.tsv"'
        rp4 = "S813"
        ro4 = strftime("+%Y-%m-%dT00:00:00Z/11", gmtime())
        print(ro4)
        f.write(f"{s}|{p}|{o}|{rp1}|{ro1}|{rp2}|{ro2}|{rp4}|{ro4}")
        f.write("\n")

+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11
+2021-02-11T00:00:00Z/11